### ISSUE TITLE
It seems this app is broken.

### ISSUE THREAD

**Issue by kenchan0130** [textlint/textlint-app#18]
I tried to do example of the README and to set `no-todo`.

<img width="907" alt="2018-12-07 21 13 21" src="https://user-images.githubusercontent.com/1155067/49647219-0d810400-fa65-11e8-896b-1ec43532f482.png">

However, I had an error following:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'textlint-rule-helper'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/path/to/Downloads/textlint.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/path/to/Library/Application Support/textlint-app/textlint/default/node_modules/textlint-rule-no-todo/src/no-todo.js:3:1)
    at Object.<anonymous> (/path/to/Library/Application Support/textlint-app/textlint/default/node_modules/textlint-rule-no-todo/lib/no-todo.js:52:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at module.exports (/path/to/Downloads/textlint.app/Contents/Resources/app.asar/node_modules/interop-require/index.js:2:13)
    at TextLintModuleLoader.loadRule (/path/to/Downloads/textlint.app/Contents/Resources/app.asar/node_modules/textlint/src/engine/textlint-module-loader.js:175:29)
    at /path/to/Downloads/textlint.app/Contents/Resources/app.asar/node_modules/textlint/src/engine/textlint-module-loader.js:57:22
    at Array.forEach (native)
    at TextLintModuleLoader.loadFromConfig (/path/to/Downloads/textlint.app/Contents/Resources/app.asar/node_modules/textlint/src/engine/textlint-module-loader.js:56:26)
    at new TextLintEngineCore (/path/to/Downloads/textlint.app/Contents/Resources/app.asar/node_modules/textlint/src/engine/textlint-engine-core.js:102:27)
    at new TextLintEngine (/path/to/Downloads/textlint.app/Contents/Resources/app.asar/node_modules/textlint/src/textlint-engine.js:58:16)
    at e.get (/path/to/Downloads/textlint.app/Contents/Resources/app.asar/app/build/webpack:/src/node/infra/textlint/TextlintAPIServer.js:30:9)
```

It seems probably that the dependencies related to `textlint-rule-no-todo` have not been downloaded.

## Environment
ProductName: Mac OS X
ProductVersion: 10.12.6
BuildVersion: 16G1618
textlint-app: 1.4.1

**Comment by kenchan0130** [comment]
Hi, this issue is fixed when I moved the app to `/Applications` or `~/Applications` directory.
Sorry for the confusion.

**Comment by azu** [comment]
No Problem.
Probably, directory's permission problem?

**Comment by kenchan0130** [comment]
> directory's permission problem?

Probably I think this is different.

I had that error in `/Users/username/Downloads/textlint.app`.
However, it is fine when I moved it to `/Users/username/Applications/textlint.app`.

Both `/Users/username/Downloads` and `/Users/username/Applications` are same permission.
