### ISSUE TITLE
Show "LOADING..." on screen (Win10 x64)

### ISSUE THREAD

**Issue by momdo** [textlint/textlint-app#7]
Steps to repro:

1. Download textlint-app-setup-1.3.1.exe
2. Install it
3. Run exe

![capture](https://cloud.githubusercontent.com/assets/8347177/25702355/9451b4cc-310b-11e7-9831-b03f878e8ead.PNG)
(This is screen shot)

Following infomation is console log by Developer tool:

C:\Users\[Username]\AppData\Local\Programs\textlint-app\resources\electron.asar\renderer\api\remote.js:234 Uncaught Error: Cannot find module 'textlint-server-package-manager'
Error: Cannot find module 'textlint-server-package-manager'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (C:\Users\[Username]\AppData\Local\Programs\textlint-app\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at EventEmitter.<anonymous> (C:\Users\[Username]\AppData\Local\Programs\textlint-app\resources\electron.asar\browser\rpc-server.js:263:70)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (C:\Users\[Username]\AppData\Local\Programs\textlint-app\resources\electron.asar\browser\api\web-contents.js:256:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (C:\Users\[Username]\AppData\Local\Programs\textlint-app\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at EventEmitter.<anonymous> (C:\Users\[Username]\AppData\Local\Programs\textlint-app\resources\electron.asar\browser\rpc-server.js:263:70)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (C:\Users\[Username]\AppData\Local\Programs\textlint-app\resources\electron.asar\browser\api\web-contents.js:256:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (C:\Users\[Username]\AppData\Local\Programs\textlint-app\resources\electron.asar\renderer\api\remote.js:234:13)
    at Object.exports.require (C:\Users\[Username]\AppData\Local\Programs\textlint-app\resources\electron.asar\renderer\api\remote.js:309:10)
    at Object.<anonymous> (file:///C:/Users/[Username]/AppData/Local/Programs/textlint-app/resources/app.asar/app/build/renderer.js:11:31015)
    at t (file:///C:/Users/[Username]/AppData/Local/Programs/textlint-app/resources/app.asar/app/build/renderer.js:1:101)
    at Object.<anonymous> (file:///C:/Users/[Username]/AppData/Local/Programs/textlint-app/resources/app.asar/app/build/renderer.js:25:149589)
    at t (file:///C:/Users/[Username]/AppData/Local/Programs/textlint-app/resources/app.asar/app/build/renderer.js:1:101)
    at Object.<anonymous> (file:///C:/Users/[Username]/AppData/Local/Programs/textlint-app/resources/app.asar/app/build/renderer.js:25:219083)
    at t (file:///C:/Users/[Username]/AppData/Local/Programs/textlint-app/resources/app.asar/app/build/renderer.js:1:101)
    at file:///C:/Users/[Username]/AppData/Local/Programs/textlint-app/resources/app.asar/app/build/renderer.js:1:484
    at file:///C:/Users/[Username]/AppData/Local/Programs/textlint-app/resources/app.asar/app/build/renderer.js:1:495

**Comment by azu** [comment]
https://github.com/textlint/textlint-app/releases/tag/v1.4.1 will resolve this issue.
